### ISSUE TITLE
Increase Code Coverage

### ISSUE THREAD

**Issue by nugrahaAdhitama** [UFO-Veteran-Jakarta/api-ufo-veteran-jakarta#41]
## Brief Description
The current code coverage is pretty good, with an average of 80%, but still far from ideal. The current code coverage threshold is 85%, which means we are still 5% short of meeting the threshold. Therefore, we need to increase our code coverage to an average of 85%.

## Acceptance Criteria
1. Ensure that unit tests cover all major functions in `achievementController.js` with edge case scenarios.
2. Implement missing tests for error handling paths in `achievementController.js` to improve branch coverage.
3. Add tests for asynchronous functions in `achievementController.js` to cover any untested branches or lines.
4. Ensure that unit tests cover all major functions in `eventController.js` with edge case scenarios.
5. Improve branch coverage in `eventController.js` by adding tests for all conditional logic.
6. Add tests for any untested or partially tested lines in `eventController.js`, especially for event creation and deletion.
7. Ensure that unit tests cover all major functions in `latestActivityController.js`, including edge cases and different input variations.
8. Implement tests for exception handling in `latestActivityController.js` to boost branch coverage.
9. Add tests for untested lines in `latestActivityController.js` related to activity updates and retrieval.
10. Increase test coverage for `partnerController.js` by adding tests for partner data validation and error handling.
11. Add missing tests for critical paths and conditionals in `partnerController.js` to improve branch coverage.
12. Ensure that all response formats in `partnerController.js` are validated in unit tests.
13. Add comprehensive tests for all CRUD operations in `workProgramController.js`.
14. Implement missing tests for conditionals in `workProgramController.js` related to program creation and updates.
15. Ensure that edge case scenarios (such as invalid data inputs) are tested in `workProgramController.js`.

**Comment by NaufalMuh11** [comment]
ok sir
