### ISSUE TITLE
Create API members

### ISSUE THREAD

**Issue by nugrahaAdhitama** [UFO-Veteran-Jakarta/api-ufo-veteran-jakarta#54]
# User Story
As an administrator of the UFO website, I want to create, read, update, and delete member information through a secure API, so that I can efficiently manage our organization's membership data and display it on our website.

# Working Branch
`54-create-api-members`

# Acceptance Criteria
1. Ensure that the POST, PUT, and DELETE endpoints can only be accessed by users who have been authenticated with a valid token.
2. Make sure to make the migration based on the existing table structure.
3. The endpoint for this API is `/api/v1/members`
3. Write unit tests for all new functions and API endpoints.
4. Implement integration tests to ensure all components work together correctly.
5. Perform load testing to ensure the API can handle expected traffic.
6. Image must be a string
7. The uploaded image must be stored in the `./public/images/members/` folder. If the folder does not exist at the start, then the directory should be created automatically.
8. The uploaded filename must be 16 random string. For example if the original filename is `Kevin Rasendriya.webp` then the filename that stored is `SN6NgaXljwVd2PHC.webp`. The random string must be consist of number, uppercase, and lowercase.
9. Images must be in WEBP format and have a maximum size of 500KB.
10. If the image is not in WEBP format, respond with HTTP Status 500 and the message: `Image must be in WEBP Format.`.

# Definition of Done
1. All acceptance criteria have been met and verified.
2. Code has been reviewed by at least one other team member.
3. All tests (unit, integration, and load) pass successfully.
4. API documentation has been updated and verified for accuracy.
5. The changes have been successfully deployed to a staging environment and tested.
6. All API endpoints have been manually tested and verified to work as expected.

# API Specification
Request:
- Method: GET
- Endpoint: `/api/v1/members`

Response:
- Success (with data):
    ```
    {
        "status": 200,
        "message": "Successfully retrieved all positions data"
        "data": [
            "id": "integer",
            "name": "string",
            "division": [
                "id": "integer",
                "name": "string",
                "image": "string"
            ],
            "position": [
                "id": "integer",
                "name": "string"
            ]
            "image": "string",
            "angaktan": "string",
            "instagram": "string",
            "linekdin": "string",
            whatsapp: "string"
            "created_at": datetime,
            "updated_at": datetime/NULL,
            "deleted_at": datetime/NULL
        ]
    }
    ```
- Success (no data):
    ```
    {
        "status": 204,
        "message": "No members data are available."
        "data": []
    }
    ```
- Error:
    ```
    {
        "status": 500,
        "message": "Failed to retrieved members data."
        "data": []
    }
    ```
    
Request:
- Method: POST
- Endpoint: `api/v1/members`
- Authorization: Bearer Token
- Body:
    ```
    {
        "name": "string",
        "division_id": "integer",
        "position_id": "integer",
        "image": "string",
        "angkatan": "string",
        "instagram": "string",
        "linkedin": "string",
        "whatsapp": "string",
        "created_at": datetime,
        "updated_at": datetime/NULL,
        "deleted_at": datetime/NULL
    }
    ```
    For `created_at`, `updated_at`, and `deleted_at` will be filled automatically and not through user input.
    
Response:
- Success:
    ```
    {
        "status": 201,
        "message": "Successfully insert member data"
        "data": [
            "id": "integer",
            "name": "string",
            "division": [
                "id": "integer",
                "name": string,
            ],
            "position": [
                "id": "integer",
                "name": "string"
            ],
            "image": "string",
            "angkatan": "string",
            "instagram": "string",
            "linkedin": "string",
            "whatsapp": "string"
            "created_at": datetime,
            "updated_at": datetime/NULL,
            "deleted_at": datetime/NULL
        ]
    }
    ```
- Error:
    - Unauthorized:
        ```
        {
            "status": 401,
            "message": "Unauthorized."
        }
        ```
    - Internal Server Error
        ```
        {
            "status": 500,
            "message": "Internal Server Error."
        }
        ```
    - Image size is too large
        ```
        {
            "status": 413,
            "message": "Imaage size is more than 500 KB."
        }
        ```
        
Request:
- Method: PATCH
- Endpoint: `api/v1/members/{id}`
- Authorization: Bearer Token
- Body:
    ```
    {
        "id": integer,
        "name": "string",
        "division_id": "integer",
        "position_id": "integer",
        "image": "string",
        "angkatan": "string",
        "instagram": "string",
        "linkedin": "string",
        "whatsapp": "string",
        "created_at": datetime,
        "updated_at": datetime/NULL,
        "deleted_at": datetime/NULL
    }
    ```
    For `created_at`, `updated_at`, and `deleted_at` will be filled automatically and not through user input.
    
    Because it uses the `PATCH` method which means the user can change only some of the desired records and not all of them. For records that are not replaced, the value will remain the same as before and not change.
    
Response:
- Success:
    ```
    {
        "status": 201,
        "message": "Successfully update member {change this with the field that been changed}"
        "data": [
            "id": "integer",
            "old_{change this with the field that been changed}": "string/integer/etc.",
            "new_{change this with the field that been changed}": "string/integer/etc.",
            "created_at": datetime,
            "updated_at": datetime,
            "deleted_at": datetime/NULL
        ]
    }
    ```

- Error:
    - Unauthorized:
        ```
        {
            "status": 401,
            "message": "Unauthorized."
        }
        ```
    - Internal Server Error
        ```
        {
            "status": 500,
            "message": "Internal Server Error."
        }
        ```
    - Member id Not Found
        ```
        {
            "status": 404,
            "message": "Member not found",
        }
        ```
    - Image size is too large
        ```
        {
            "status": 413,
            "message": "Imaage size is more than 500 KB."
        }
        ```
        
Request:
- Method: DELETE
- Endpoint: `api/v1/members/{slug}`
- Authorization: Bearer Token
    
Response:
- Success:
    ```
    {
        "status": 200,
        "message": "Successfully delete member data"
        "data": [
            "id": "integer",
            "name": "string",
            "division": [
                "id": "integer",
                "name": string,
            ],
            "position": [
                "id": "integer",
                "name": "string"
            ],
            "image": "string",
            "angkatan": "string",
            "instagram": "string",
            "linkedin": "string",
            "whatsapp": "string"
            "created_at": datetime,
            "updated_at": datetime/NULL,
            "deleted_at": datetime/NULL
        ]
    }
    ```
- Error:
    - Unauthorized:
        ```
        {
            "status": 401,
            "message": "Unauthorized."
        }
        ```
    - Internal Server Error
        ```
        {
            "status": 500,
            "message": "Internal Server Error."
        }
        ```
    - Member Id Not Found
        ```
        {
            "status": 404,
            "message": "Member not found."
        }
        ```

**Comment by NaufalMuh11** [comment]
Ok Sir
